In [57]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from mpl_toolkits.mplot3d import Axes3D
from joblib import dump

%matplotlib notebook

In [58]:
dataset_frame = pd.read_csv("dataset_frame.csv")

In [59]:
dataset_frame.describe()

        Unnamed: 0   importance     latitude    longitude        prices
count  2000.000000  1192.000000  1192.000000  1192.000000  2.000000e+03
mean    999.500000     0.555754    51.038335    -2.072862  1.021149e+06
std     577.494589     0.088966     4.449673    12.285143  3.672325e+06
min       0.000000     0.201000   -32.972086   -83.427979  5.000000e+02
25%     499.750000     0.510000    51.454632    -0.197044  3.797122e+05
50%     999.500000     0.521000    51.504171    -0.126439  5.215000e+05
75%    1499.250000     0.610000    51.563265    -0.036370  8.200000e+05
max    1999.000000     0.910000    52.192419    27.928211  1.098000e+08

In [60]:
dataset_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    2000 non-null   int64
 1   addresses     2000 non-null   object
 2   build_status  2000 non-null   object
 3   category      1192 non-null   object
 4   flat_type     1826 non-null   object
 5   importance    1192 non-null   float64
 6   latitude      1192 non-null   float64
 7   lease_type    2000 non-null   object
 8   longitude     1192 non-null   float64
 9   prices        2000 non-null   float64
 10  sale_dates    2000 non-null   object
 11  subcategory   1192 non-null   object
dtypes: float64(4), int64(1), object(7)
memory usage: 187.6+ KB

In [61]:
# We add a new parameter, which we will use to exclude anomalous lat lon coordinates from bad Open Street Map API data.
    
dataset_frame["latitude_z_score"] = (dataset_frame.latitude - dataset_frame.latitude.mean()) / dataset_frame.latitude.std()
dataset_frame["longitude_z_score"] = (dataset_frame.longitude - dataset_frame.longitude.mean()) / dataset_frame.longitude.std()

In [62]:
dataset_frame.latitude_z_score.describe()

count    1.192000e+03
mean     2.905953e-16
std      1.000000e+00
min     -1.888013e+01
25%      9.355684e-02
50%      1.046899e-01
75%      1.179705e-01
max      2.593637e-01
Name: latitude_z_score, dtype: float64

In [63]:
dataset_frame.longitude_z_score.describe()

count    1.192000e+03
mean    -2.086325e-17
std      1.000000e+00
min     -6.622236e+00
25%      1.526900e-01
50%      1.584372e-01
75%      1.657687e-01
max      2.442061e+00
Name: longitude_z_score, dtype: float64

In [64]:
dropped_nas = dataset_frame.dropna()
dropped_nas.describe()

,Unnamed: 0,importance,latitude,longitude,prices,latitude_z_score,longitude_z_score
count,1072.000000,1072.000000,1072.000000,1072.000000,1.072000e+03,1072.000000,1072.000000
mean,983.026119,0.553241,51.013960,-2.085823,8.859616e+05,-0.005478,-0.001055
std,580.837275,0.085985,4.665087,12.397957,1.199908e+06,1.048411,1.009183
min,0.000000,0.201000,-32.972086,-83.427979,8.550000e+04,-18.880132,-6.622236
25%,467.500000,0.510000,51.454195,-0.198821,4.298750e+05,0.093459,0.152545
50%,983.500000,0.521000,51.504048,-0.122793,6.090000e+05,0.104662,0.158734
75%,1466.500000,0.610000,51.568233,-0.034571,9.536250e+05,0.119087,0.165915
max,1999.000000,0.830078,52.192419,27.928211,1.785000e+07,0.259364,2.442061

In [65]:
dropped_nas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1072 entries, 0 to 1999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         1072 non-null   int64
 1   addresses          1072 non-null   object
 2   build_status       1072 non-null   object
 3   category           1072 non-null   object
 4   flat_type          1072 non-null   object
 5   importance         1072 non-null   float64
 6   latitude           1072 non-null   float64
 7   lease_type         1072 non-null   object
 8   longitude          1072 non-null   float64
 9   prices             1072 non-null   float64
 10  sale_dates         1072 non-null   object
 11  subcategory        1072 non-null   object
 12  latitude_z_score   1072 non-null   float64
 13  longitude_z_score  1072 non-null   float64
dtypes: float64(6), int64(1), object(7)
memory usage: 125.6+ KB

In [66]:
# We filter out any observations where our latitude or longitude values are more than 1 standard deviations away from the mean.
# All the observations are in London, so any latitude longitude coordinates beyond this range are probably wrong.
df = dropped_nas
df = df[df.latitude_z_score.abs() < 3]
df = df[df.longitude_z_score.abs() < 3]
df = df.drop(df.columns[0],axis=1)

In [67]:
x = df.longitude
y = df.latitude
fig1 = plt.figure()
scat = plt.scatter(x, y)

In [68]:
# From the above, we can see that while the first Z score based latitude longitude filtering eliminated most wholly inaccurate
# OSM API response data, it did not eliminate data which was broadly within 3.s.d. on the original dataset, but actually
# incorrect "locally" for London addresses. These anomalies appear to be off near Leeds!
# If we run a scatter graph of the Z-scores from the original dataset, our problem becomes obvious.

x2 = df.longitude_z_score
y2 = df.latitude_z_score
fig2 = plt.figure()
scat = plt.scatter(x2, y2)

In [69]:
# We will run our filter again by reassiging the latitude and longitude Z-scores and filtering appropriately.

df["latitude_z_score"] = (df.latitude - df.latitude.mean()) / df.latitude.std()
df["longitude_z_score"] = (df.longitude - df.longitude.mean()) / df.longitude.std()
df = df[df.latitude_z_score.abs() < 3]
df = df[df.longitude_z_score.abs() < 3]
df.drop(df.columns[0],axis=1)

x3 = df.longitude
y3 = df.latitude
fig3 = plt.figure()
scat = plt.scatter(x3, y3)

In [70]:
# We will also create dummy variables for all our non-numerical dataseries.
build_status_dummies = pd.get_dummies(df.build_status)
flat_type_dummies = pd.get_dummies(df.flat_type)
lease_type_dummies = pd.get_dummies(df.lease_type)
category_dummies = pd.get_dummies(df.category)
subcategory_dummies = pd.get_dummies(df.subcategory)


dataframes_set = [df, build_status_dummies, flat_type_dummies, lease_type_dummies, category_dummies, subcategory_dummies]
df = pd.concat(dataframes_set, axis=1).reset_index(drop=True)
df = df.drop(df.columns[0],axis=1)

In [71]:
df.head()

,build_status,category,flat_type,importance,latitude,lease_type,longitude,prices,sale_dates,subcategory,...,residential,restaurant,secondary,service,studio,suburb,tertiary,trunk,uncategoryified,yes
0,Non-Newbuild,highway,Terraced,0.520,51.576340,Freehold,-0.031657,560000.0,2018-10-29,residential,...,True,False,False,False,False,False,False,False,False,False
1,Non-Newbuild,place,Terraced,0.421,51.461539,Freehold,-0.129039,1550000.0,2018-10-26,house,...,False,False,False,False,False,False,False,False,False,False
2,Non-Newbuild,place,Terraced,0.421,51.595599,Freehold,-0.033173,1575000.0,2018-10-26,house,...,False,False,False,False,False,False,False,False,False,False
3,Non-Newbuild,highway,Semi Detached,0.610,51.593683,Freehold,-0.183207,1100000.0,2018-10-26,primary,...,False,False,False,False,False,False,False,False,False,False
4,Non-Newbuild,highway,Flat,0.620,51.580105,Leasehold,-0.012300,395000.0,2018-10-26,residential,...,True,False,False,False,False,False,False,False,False,False

In [72]:
cols_to_drop = ["build_status",
                "flat_type",
                "lease_type",
                "category",
                "subcategory",
                "latitude_z_score",
                "longitude_z_score"]

fdf = df.drop(cols_to_drop, axis=1).reset_index(drop=True)

In [73]:
# We save our last dataset before using this in K-Means clustering labelling.
fdf.to_csv("final_dataset_frame.csv")
fdf.to_json("final_dataset_frame.json")

In [74]:
x = fdf.longitude
y = fdf.latitude
z = fdf.prices

fig1 = plt.figure()
ax = Axes3D(fig1)

ax.scatter(x, y, z)

In [75]:
# We will check to see if we have any more non-numeric data, if so, we will drop these series:
fdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1037 entries, 0 to 1036
Data columns (total 35 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   importance       1037 non-null   float64
 1   latitude         1037 non-null   float64
 2   longitude        1037 non-null   float64
 3   prices           1037 non-null   float64
 4   sale_dates       1037 non-null   object
 5   Non-Newbuild     1037 non-null   bool
 6   Detached         1037 non-null   bool
 7   Flat             1037 non-null   bool
 8   Semi Detached    1037 non-null   bool
 9   Terraced         1037 non-null   bool
 10  Freehold         1037 non-null   bool
 11  Leasehold        1037 non-null   bool
 12  amenity          1037 non-null   bool
 13  building         1037 non-null   bool
 14  highway          1037 non-null   bool
 15  landuse          1037 non-null   bool
 16  place            1037 non-null   bool
 17  cafe             1037 non-null   bool
 18  fast_food        1037 non-null   bool
 19  footway          1037 non-null   bool
 20  house            1037 non-null   bool
 21  living_street    1037 non-null   bool
 22  neighbourhood    1037 non-null   bool
 23  pedestrian       1037 non-null   bool
 24  primary          1037 non-null   bool
 25  residential      1037 non-null   bool
 26  restaurant       1037 non-null   bool
 27  secondary        1037 non-null   bool
 28  service          1037 non-null   bool
 29  studio           1037 non-null   bool
 30  suburb           1037 non-null   bool
 31  tertiary         1037 non-null   bool
 32  trunk            1037 non-null   bool
 33  uncategoryified  1037 non-null   bool
 34  yes              1037 non-null   bool
dtypes: bool(30), float64(4), object(1)
memory usage: 71.0+ KB

In [76]:
# It looks like we forgot to get rid of the addresses, so we will do that now.
# fdf = fdf.drop(["addresses"], axis=1)

In [77]:
# We can now begin the process of clustering our datapoints into lat-lon clusters.

# We will create our dataframe for the K-means Clustering method for labelling our data.
kmm_X = pd.DataFrame([fdf.latitude, fdf.longitude]).T

# We will specify our model to use 10 clusters; we will not explore cluster optimisation here as it is beyond the scope of this
# exercise.

num_clusters = 10
kmeans = KMeans(n_clusters=num_clusters, max_iter=6000, algorithm="lloyd", random_state=0)
kmm = kmeans.fit(kmm_X)
id_label = kmm.labels_

In [78]:
# We will store our model via a joblib dump

dump(kmm, '../k_means_clustering_model_deploy.joblib')

['k_means_clustering_model.joblib']

In [79]:
# We will now plot our clusters to see if the labels look correct. We also plot our cluster centres.
fig2 = plt.figure()
for i in range(num_clusters):
    cluster = np.where(id_label == i)[0]
    plt.scatter(kmm_X.latitude[cluster].values, kmm_X.longitude[cluster].values)
plt.scatter(kmm.cluster_centers_[:,0], kmm.cluster_centers_[:,1], c="black", marker="X")

In [80]:
# We will now add our cluster labels back to our orginal final dataset frame, and derive dummies.
kmm_label_dummies = pd.get_dummies(kmm.labels_)
fdf = pd.concat([fdf, kmm_label_dummies], axis=1)

In [81]:
# Checking our final variable set.
fdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1037 entries, 0 to 1036
Data columns (total 45 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   importance       1037 non-null   float64
 1   latitude         1037 non-null   float64
 2   longitude        1037 non-null   float64
 3   prices           1037 non-null   float64
 4   sale_dates       1037 non-null   object
 5   Non-Newbuild     1037 non-null   bool
 6   Detached         1037 non-null   bool
 7   Flat             1037 non-null   bool
 8   Semi Detached    1037 non-null   bool
 9   Terraced         1037 non-null   bool
 10  Freehold         1037 non-null   bool
 11  Leasehold        1037 non-null   bool
 12  amenity          1037 non-null   bool
 13  building         1037 non-null   bool
 14  highway          1037 non-null   bool
 15  landuse          1037 non-null   bool
 16  place            1037 non-null   bool
 17  cafe             1037 non-null   bool
 18  fast_food        1037 non-null   bool
 19  footway          1037 non-null   bool
 20  house            1037 non-null   bool
 21  living_street    1037 non-null   bool
 22  neighbourhood    1037 non-null   bool
 23  pedestrian       1037 non-null   bool
 24  primary          1037 non-null   bool
 25  residential      1037 non-null   bool
 26  restaurant       1037 non-null   bool
 27  secondary        1037 non-null   bool
 28  service          1037 non-null   bool
 29  studio           1037 non-null   bool
 30  suburb           1037 non-null   bool
 31  tertiary         1037 non-null   bool
 32  trunk            1037 non-null   bool
 33  uncategoryified  1037 non-null   bool
 34  yes              1037 non-null   bool
 35  0                1037 non-null   bool
 36  1                1037 non-null   bool
 37  2                1037 non-null   bool
 38  3                1037 non-null   bool
 39  4                1037 non-null   bool
 40  5                1037 non-null   bool
 41  6                1037 non-null   bool
 42  7                1037 non-null   bool
 43  8                1037 non-null   bool
 44  9                1037 non-null   bool
dtypes: bool(40), float64(4), object(1)
memory usage: 81.1+ KB

In [82]:
# A final peek at our data to ensure it looks vaguely sensible.
fdf.describe()

        importance     latitude    longitude        prices
count  1037.000000  1037.000000  1037.000000  1.037000e+03
mean      0.558884    51.513592    -0.114196  8.933299e+05
std       0.079764     0.066217     0.100994  1.217876e+06
min       0.310000    51.322560    -0.423773  8.550000e+04
25%       0.510000    51.458072    -0.193035  4.295000e+05
50%       0.521000    51.507699    -0.119659  6.125000e+05
75%       0.610000    51.570414    -0.032794  9.570000e+05
max       0.830078    51.659421     0.198871  1.785000e+07

In [83]:
fdf.head()

,importance,latitude,longitude,prices,sale_dates,Non-Newbuild,Detached,Flat,Semi Detached,Terraced,...,0,1,2,3,4,5,6,7,8,9
0,0.520,51.576340,-0.031657,560000.0,2018-10-29,True,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False
1,0.421,51.461539,-0.129039,1550000.0,2018-10-26,True,False,False,False,True,...,False,False,False,False,False,False,False,False,False,True
2,0.421,51.595599,-0.033173,1575000.0,2018-10-26,True,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False
3,0.610,51.593683,-0.183207,1100000.0,2018-10-26,True,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
4,0.620,51.580105,-0.012300,395000.0,2018-10-26,True,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False

In [84]:
# We will save our dataset in a CSV for use in the next Scratchpad where we explore Random Forest Models, which we will pickle.
# We will use our pickled model as the basis for our RESTful API.
fdf.to_csv("random_forest_dataset.csv")
fdf.to_json("random_forest_dataset.json")