In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error as MAE
from datetime import datetime
from matplotlib import pyplot as plt
from joblib import dump

%matplotlib notebook

In [2]:
# First we load our dataset from the previous scratchpad with K-means Cluster Lables.

data_filepath = "random_forest_dataset.csv"
df = pd.read_csv(data_filepath)

In [3]:
# We will check our data's profile before proceeding.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1037 entries, 0 to 1036
Data columns (total 46 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       1037 non-null   int64
 1   importance       1037 non-null   float64
 2   latitude         1037 non-null   float64
 3   longitude        1037 non-null   float64
 4   prices           1037 non-null   float64
 5   sale_dates       1037 non-null   object
 6   Non-Newbuild     1037 non-null   bool
 7   Detached         1037 non-null   bool
 8   Flat             1037 non-null   bool
 9   Semi Detached    1037 non-null   bool
 10  Terraced         1037 non-null   bool
 11  Freehold         1037 non-null   bool
 12  Leasehold        1037 non-null   bool
 13  amenity          1037 non-null   bool
 14  building         1037 non-null   bool
 15  highway          1037 non-null   bool
 16  landuse          1037 non-null   bool
 17  place            1037 non-null   bool
 18  cafe             1037 non-null   bool
 19  fast_food        1037 non-null   bool
 20  footway          1037 non-null   bool
 21  house            1037 non-null   bool
 22  living_street    1037 non-null   bool
 23  neighbourhood    1037 non-null   bool
 24  pedestrian       1037 non-null   bool
 25  primary          1037 non-null   bool
 26  residential      1037 non-null   bool
 27  restaurant       1037 non-null   bool
 28  secondary        1037 non-null   bool
 29  service          1037 non-null   bool
 30  studio           1037 non-null   bool
 31  suburb           1037 non-null   bool
 32  tertiary         1037 non-null   bool
 33  trunk            1037 non-null   bool
 34  uncategoryified  1037 non-null   bool
 35  yes              1037 non-null   bool
 36  0                1037 non-null   bool
 37  1                1037 non-null   bool
 38  2                1037 non-null   bool
 39  3                1037 non-null   bool
 40  4                1037 non-null   bool
 41  5                1037 non-null   bool
 42  6                1037 non-null   bool
 43  7                1037 non-null   bool
 44  8                1037 non-null   bool
 45  9                1037 non-null   bool
dtypes: bool(40), float64(4), int64(1), object(1)
memory usage: 89.2+ KB

In [4]:
# We need to drop our first unnamed column, which is an artefact of importing the dataset from a CSV.

df = df.drop(df.columns[0], axis=1)
df.head()

,importance,latitude,longitude,prices,sale_dates,Non-Newbuild,Detached,Flat,Semi Detached,Terraced,...,0,1,2,3,4,5,6,7,8,9
0,0.520,51.576340,-0.031657,560000.0,2018-10-29,True,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False
1,0.421,51.461539,-0.129039,1550000.0,2018-10-26,True,False,False,False,True,...,False,False,False,False,False,False,False,False,False,True
2,0.421,51.595599,-0.033173,1575000.0,2018-10-26,True,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False
3,0.610,51.593683,-0.183207,1100000.0,2018-10-26,True,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
4,0.620,51.580105,-0.012300,395000.0,2018-10-26,True,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False

In [5]:
# We need to convert our sales_dates back to datetime objects:

df.sale_dates = [datetime.strptime(date, "%Y-%m-%d") for date in df.sale_dates]

In [6]:
# Our sales dates should now look a lot better.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1037 entries, 0 to 1036
Data columns (total 45 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   importance       1037 non-null   float64
 1   latitude         1037 non-null   float64
 2   longitude        1037 non-null   float64
 3   prices           1037 non-null   float64
 4   sale_dates       1037 non-null   datetime64[ns]
 5   Non-Newbuild     1037 non-null   bool
 6   Detached         1037 non-null   bool
 7   Flat             1037 non-null   bool
 8   Semi Detached    1037 non-null   bool
 9   Terraced         1037 non-null   bool
 10  Freehold         1037 non-null   bool
 11  Leasehold        1037 non-null   bool
 12  amenity          1037 non-null   bool
 13  building         1037 non-null   bool
 14  highway          1037 non-null   bool
 15  landuse          1037 non-null   bool
 16  place            1037 non-null   bool
 17  cafe             1037 non-null   bool
 18  fast_food        1037 non-null   bool
 19  footway          1037 non-null   bool
 20  house            1037 non-null   bool
 21  living_street    1037 non-null   bool
 22  neighbourhood    1037 non-null   bool
 23  pedestrian       1037 non-null   bool
 24  primary          1037 non-null   bool
 25  residential      1037 non-null   bool
 26  restaurant       1037 non-null   bool
 27  secondary        1037 non-null   bool
 28  service          1037 non-null   bool
 29  studio           1037 non-null   bool
 30  suburb           1037 non-null   bool
 31  tertiary         1037 non-null   bool
 32  trunk            1037 non-null   bool
 33  uncategoryified  1037 non-null   bool
 34  yes              1037 non-null   bool
 35  0                1037 non-null   bool
 36  1                1037 non-null   bool
 37  2                1037 non-null   bool
 38  3                1037 non-null   bool
 39  4                1037 non-null   bool
 40  5                1037 non-null   bool
 41  6                1037 non-null   bool
 42  7                1037 non-null   bool
 43  8                1037 non-null   bool
 44  9                1037 non-null   bool
dtypes: bool(40), datetime64[ns](1), float64(4)
memory usage: 81.1 KB

In [7]:
df.head()

,importance,latitude,longitude,prices,sale_dates,Non-Newbuild,Detached,Flat,Semi Detached,Terraced,...,0,1,2,3,4,5,6,7,8,9
0,0.520,51.576340,-0.031657,560000.0,2018-10-29,True,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False
1,0.421,51.461539,-0.129039,1550000.0,2018-10-26,True,False,False,False,True,...,False,False,False,False,False,False,False,False,False,True
2,0.421,51.595599,-0.033173,1575000.0,2018-10-26,True,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False
3,0.610,51.593683,-0.183207,1100000.0,2018-10-26,True,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
4,0.620,51.580105,-0.012300,395000.0,2018-10-26,True,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False

In [8]:
# We will now look at the summary stats of our data to see if we have something sensible.

df.describe()

,importance,latitude,longitude,prices,sale_dates
count,1037.000000,1037.000000,1037.000000,1.037000e+03,1037
mean,0.558884,51.513592,-0.114196,8.933299e+05,2018-10-08 20:08:06.017357824
min,0.310000,51.322560,-0.423773,8.550000e+04,2018-09-28 00:00:00
25%,0.510000,51.458072,-0.193035,4.295000e+05,2018-10-03 00:00:00
50%,0.521000,51.507699,-0.119659,6.125000e+05,2018-10-08 00:00:00
75%,0.610000,51.570414,-0.032794,9.570000e+05,2018-10-15 00:00:00
max,0.830078,51.659421,0.198871,1.785000e+07,2018-10-29 00:00:00
std,0.079764,0.066217,0.100994,1.217876e+06,NaN

In [9]:
# We will now set up our dependent variable y, and our independent variables X.

y = df.prices
X = df.drop(["prices"], axis=1)

# We will sadly need to drop sale_dates too, as datetime variables are not appropriate for this type of model.
# Another day, we can explore the impact of date of sale category dummies on the sale price.

X = X.drop(["sale_dates"], axis=1)

In [10]:
# We will inspect our final list of X variables feeding our model.
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1037 entries, 0 to 1036
Data columns (total 43 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   importance       1037 non-null   float64
 1   latitude         1037 non-null   float64
 2   longitude        1037 non-null   float64
 3   Non-Newbuild     1037 non-null   bool
 4   Detached         1037 non-null   bool
 5   Flat             1037 non-null   bool
 6   Semi Detached    1037 non-null   bool
 7   Terraced         1037 non-null   bool
 8   Freehold         1037 non-null   bool
 9   Leasehold        1037 non-null   bool
 10  amenity          1037 non-null   bool
 11  building         1037 non-null   bool
 12  highway          1037 non-null   bool
 13  landuse          1037 non-null   bool
 14  place            1037 non-null   bool
 15  cafe             1037 non-null   bool
 16  fast_food        1037 non-null   bool
 17  footway          1037 non-null   bool
 18  house            1037 non-null   bool
 19  living_street    1037 non-null   bool
 20  neighbourhood    1037 non-null   bool
 21  pedestrian       1037 non-null   bool
 22  primary          1037 non-null   bool
 23  residential      1037 non-null   bool
 24  restaurant       1037 non-null   bool
 25  secondary        1037 non-null   bool
 26  service          1037 non-null   bool
 27  studio           1037 non-null   bool
 28  suburb           1037 non-null   bool
 29  tertiary         1037 non-null   bool
 30  trunk            1037 non-null   bool
 31  uncategoryified  1037 non-null   bool
 32  yes              1037 non-null   bool
 33  0                1037 non-null   bool
 34  1                1037 non-null   bool
 35  2                1037 non-null   bool
 36  3                1037 non-null   bool
 37  4                1037 non-null   bool
 38  5                1037 non-null   bool
 39  6                1037 non-null   bool
 40  7                1037 non-null   bool
 41  8                1037 non-null   bool
 42  9                1037 non-null   bool
dtypes: bool(40), float64(3)
memory usage: 64.9 KB

In [11]:
# We describe our summary stats for price data, to get a feel for the distribution, and what could be sensible as model output.
y.describe()

count    1.037000e+03
mean     8.933299e+05
std      1.217876e+06
min      8.550000e+04
25%      4.295000e+05
50%      6.125000e+05
75%      9.570000e+05
max      1.785000e+07
Name: prices, dtype: float64

In [12]:
# We also explore our numerical (these should be the only type!) independent variables for a gauge of their distribution.
X.describe()

        importance     latitude    longitude
count  1037.000000  1037.000000  1037.000000
mean      0.558884    51.513592    -0.114196
std       0.079764     0.066217     0.100994
min       0.310000    51.322560    -0.423773
25%       0.510000    51.458072    -0.193035
50%       0.521000    51.507699    -0.119659
75%       0.610000    51.570414    -0.032794
max       0.830078    51.659421     0.198871

In [13]:
forest_model_naive = RandomForestRegressor(random_state=1)
forest_model_naive.fit(X, y)
y_hat = forest_model_naive.predict(X)

In [14]:
# We can observe the Mean Absolute Error of our naive model without splitting  the data into a training set.

MAE(y, y_hat)

136228.04226569316

In [15]:
# We will now split our data and look at the out of sample predictive power of our trained model instead.

train_X, val_X, train_y, val_y = train_test_split(X, y, random_state=0)

forest_model_trained = RandomForestRegressor(random_state=1)
forest_model_trained.fit(train_X, train_y)
y_hat_trained = forest_model_trained.predict(val_X)

In [16]:
# We can now look at our out-of-sample model prediction MAE for verification.

MAE(val_y, y_hat_trained)

347272.9123397436

In [17]:
# It becomes abundantly clear that our naive model is better in this low sample size situation.
# We will optimise it as best as we can given other parameters we can control, like maximum tree leaf nodes.

def get_MAE(max_leaf_nodes, X, y, model_type):
    model = model_type(max_leaf_nodes=max_leaf_nodes, random_state=0)
    model.fit(X, y)
    y_hat = model.predict(X)
    return MAE(y, y_hat)

In [18]:
rfr_utility_func_data = {'max_leaf_nodes' : [], 'MAE': []}

for max_leaf_nodes in [i**2 for i in range(2, 50)]:
    my_mae = get_MAE(max_leaf_nodes, X, y, RandomForestRegressor)
    rfr_utility_func_data['max_leaf_nodes'].append(max_leaf_nodes)
    rfr_utility_func_data['MAE'].append(my_mae)

In [19]:
rfr_utility_function_plot = pd.DataFrame.from_dict(rfr_utility_func_data)
rfr_minimum_mae = rfr_utility_function_plot.MAE.min()
rfr_best_max_nodes = rfr_utility_function_plot.max_leaf_nodes[rfr_utility_function_plot.MAE.idxmin()]

print(f"The minimum MAE is {rfr_minimum_mae} in an RFR model with {rfr_best_max_nodes} maximum leaf nodes")

plt.plot(rfr_utility_function_plot.max_leaf_nodes, rfr_utility_function_plot.MAE)

The minimum MAE is 136126.4675483308 in an RFR model with 676 maximum leaf nodes

In [20]:
# We will pick this model with the suggested maximum leaf nodes above, and serialise it for use in our API.

serialised_model = RandomForestRegressor(random_state=1, max_leaf_nodes=rfr_best_max_nodes)
serialised_model.fit(X, y)

RandomForestRegressor(max_leaf_nodes=np.int64(676), random_state=1)

In [21]:
# We will now dump the model to a file via joblib, which handles numpy arrays better than pickle.
dump(serialised_model, "serialised_random_forest_regressor.joblib")

['serialised_random_forest_regressor.joblib']